server:
  port: 8888
spring:
 application:
  name: lib-manage
 datasource:
  url: jdbc:mysql://localhost/lib-management?createDatabaseIfNotExist=true
  username: ENC(/2DTGgJn0emccDLLK2KpfebnjLPqULku)
  password: ENC(JJtjBGndGYWpIjSRM63DOfj9C3Mbbldr)
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   properties:
    hibernate:
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
     dialect: org.hibernate.dialect.MySQLDialect
     format-sql: true
   show-sql: true
   hibernate:
   # Hibernate ddl auto (none, create, create-drop, validate, update)
     ddl-auto: update
jasypt:
  encryptor:
    password: watermelon
    algorithm: PBEWithMD5AndDES
jwt:
  signerKey: xIozWdD9r3RiqzaaRxJTYMvVvoKVk4G9Iq4kZ7ZEXXpePPxgtRQKj/O43HYbWhKy
redis:
  server:
    host: 127.0.0.1
    port: 6379
